// mockData.js

export const mockCorrelationData = [
    {
        feature_1_name: "Gene A",
        feature_2_name: "Gene B",
        count: 50,
        spearman_correlation: 0.85,
        spearman_p_value: 0.0001,
        fdr_adjusted_p_value: 0.001,
    },
    {
        feature_1_name: "Gene C",
        feature_2_name: "Gene D",
        count: 45,
        spearman_correlation: 0.75,
        spearman_p_value: 0.002,
        fdr_adjusted_p_value: 0.01,
    },
    {
        feature_1_name: "Gene A",
        feature_2_name: "Gene E",
        count: 40,
        spearman_correlation: 0.65,
        spearman_p_value: 0.03,
        fdr_adjusted_p_value: 0.05,
    },
    {
        feature_1_name: "Gene F",
        feature_2_name: "Gene G",
        count: 30,
        spearman_correlation: 0.55,
        spearman_p_value: 0.05,
        fdr_adjusted_p_value: 0.06,
    },
    {
        feature_1_name: "Gene H",
        feature_2_name: "Gene I",
        count: 35,
        spearman_correlation: 0.40,
        spearman_p_value: 0.12,
        fdr_adjusted_p_value: 0.2,
    },
    {
        feature_1_name: "Gene J",
        feature_2_name: "Gene K",
        count: 25,
        spearman_correlation: 0.30,
        spearman_p_value: 0.22,
        fdr_adjusted_p_value: 0.3,
    },
    {
        feature_1_name: "Gene L",
        feature_2_name: "Gene M",
        count: 60,
        spearman_correlation: 0.90,
        spearman_p_value: 0.00005,
        fdr_adjusted_p_value: 0.0005,
    },
    {
        feature_1_name: "Gene N",
        feature_2_name: "Gene O",
        count: 15,
        spearman_correlation: 0.15,
        spearman_p_value: 0.5,
        fdr_adjusted_p_value: 0.6,
    },
    {
        feature_1_name: "Gene P",
        feature_2_name: "Gene Q",
        count: 10,
        spearman_correlation: 0.05,
        spearman_p_value: 0.9,
        fdr_adjusted_p_value: 0.95,
    },
    {
        feature_1_name: "Gene R",
        feature_2_name: "Gene S",
        count: 80,
        spearman_correlation: 0.88,
        spearman_p_value: 0.0002,
        fdr_adjusted_p_value: 0.002,
    },
    {
        feature_1_name: "Gene T",
        feature_2_name: "Gene U",
        count: 55,
        spearman_correlation: 0.72,
        spearman_p_value: 0.003,
        fdr_adjusted_p_value: 0.015,
    },
    {
        feature_1_name: "Gene V",
        feature_2_name: "Gene W",
        count: 42,
        spearman_correlation: 0.67,
        spearman_p_value: 0.01,
        fdr_adjusted_p_value: 0.02,
    },
    {
        feature_1_name: "Gene X",
        feature_2_name: "Gene Y",
        count: 34,
        spearman_correlation: 0.43,
        spearman_p_value: 0.08,
        fdr_adjusted_p_value: 0.1,
    },
    {
        feature_1_name: "Gene Z",
        feature_2_name: "Gene AA",
        count: 20,
        spearman_correlation: 0.25,
        spearman_p_value: 0.3,
        fdr_adjusted_p_value: 0.4,
    },
    {
        feature_1_name: "Gene AB",
        feature_2_name: "Gene AC",
        count: 70,
        spearman_correlation: 0.92,
        spearman_p_value: 0.00001,
        fdr_adjusted_p_value: 0.0003,
    },
    {
        feature_1_name: "Gene AD",
        feature_2_name: "Gene AE",
        count: 65,
        spearman_correlation: 0.82,
        spearman_p_value: 0.0008,
        fdr_adjusted_p_value: 0.008,
    },
];
