# Generated by Django 5.1.2 on 2024-11-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_cellline_delete_geneexpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cellline',
            name='depmap_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='CellLineFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('cellline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cellline')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.feature')),
            ],
        ),
    ]
