# Generated by Django 5.1.2 on 2024-11-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_cellline_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.feature'),
        ),
    ]
