# Generated by Django 5.1.2 on 2024-11-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_cellline_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellLine',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
