# Generated by Django 5.1.2 on 2025-01-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('spearman_corr', models.FloatField(default=0)),
                ('spearman_pvalue', models.FloatField(default=0)),
                ('feature1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature1', to='database.feature')),
                ('feature2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature2', to='database.feature')),
            ],
            options={
                'unique_together': {('feature1', 'feature2')},
            },
        ),
    ]
