# Generated by Django 5.1.2 on 2025-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='data_type',
            field=models.CharField(choices=[('num', 'Numerical'), ('cat', 'Categorical')], default='num', max_length=3),
        ),
    ]
