# Generated by Django 5.1.2 on 2025-02-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_feature_data_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CellLine',
            new_name='Nuclear',
        ),
    ]
