# Generated by Django 5.1.2 on 2025-02-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_cellline_nuclear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mole_GlobalChromatin',
            fields=[
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.feature')),
                ('ACH-000657', models.FloatField(blank=True, null=True)),
                ('ACH-001278', models.FloatField(blank=True, null=True)),
                ('ACH-000713', models.FloatField(blank=True, null=True)),
                ('ACH-001042', models.FloatField(blank=True, null=True)),
                ('ACH-000256', models.FloatField(blank=True, null=True)),
                ('ACH-000278', models.FloatField(blank=True, null=True)),
                ('ACH-000123', models.FloatField(blank=True, null=True)),
                ('ACH-001048', models.FloatField(blank=True, null=True)),
                ('ACH-000608', models.FloatField(blank=True, null=True)),
                ('ACH-001063', models.FloatField(blank=True, null=True)),
                ('ACH-000906', models.FloatField(blank=True, null=True)),
                ('ACH-000574', models.FloatField(blank=True, null=True)),
                ('ACH-000542', models.FloatField(blank=True, null=True)),
                ('ACH-002140', models.FloatField(blank=True, null=True)),
                ('ACH-000324', models.FloatField(blank=True, null=True)),
                ('ACH-000237', models.FloatField(blank=True, null=True)),
                ('ACH-000132', models.FloatField(blank=True, null=True)),
                ('ACH-002149', models.FloatField(blank=True, null=True)),
                ('ACH-000524', models.FloatField(blank=True, null=True)),
                ('ACH-000796', models.FloatField(blank=True, null=True)),
                ('ACH-000001', models.FloatField(blank=True, null=True)),
                ('ACH-000116', models.FloatField(blank=True, null=True)),
                ('ACH-000704', models.FloatField(blank=True, null=True)),
                ('ACH-000091', models.FloatField(blank=True, null=True)),
                ('ACH-000688', models.FloatField(blank=True, null=True)),
                ('ACH-000291', models.FloatField(blank=True, null=True)),
                ('ACH-002181', models.FloatField(blank=True, null=True)),
                ('ACH-002182', models.FloatField(blank=True, null=True)),
                ('ACH-000617', models.FloatField(blank=True, null=True)),
                ('ACH-001151', models.FloatField(blank=True, null=True)),
                ('ACH-000696', models.FloatField(blank=True, null=True)),
                ('ACH-000527', models.FloatField(blank=True, null=True)),
                ('ACH-000947', models.FloatField(blank=True, null=True)),
                ('ACH-000443', models.FloatField(blank=True, null=True)),
                ('ACH-000646', models.FloatField(blank=True, null=True)),
                ('ACH-000409', models.FloatField(blank=True, null=True)),
                ('ACH-000663', models.FloatField(blank=True, null=True)),
                ('ACH-001374', models.FloatField(blank=True, null=True)),
                ('ACH-001628', models.FloatField(blank=True, null=True)),
                ('ACH-001630', models.FloatField(blank=True, null=True)),
                ('ACH-001632', models.FloatField(blank=True, null=True)),
                ('ACH-000719', models.FloatField(blank=True, null=True)),
                ('ACH-000701', models.FloatField(blank=True, null=True)),
                ('ACH-000811', models.FloatField(blank=True, null=True)),
                ('ACH-000460', models.FloatField(blank=True, null=True)),
                ('ACH-001403', models.FloatField(blank=True, null=True)),
                ('ACH-000048', models.FloatField(blank=True, null=True)),
                ('ACH-000885', models.FloatField(blank=True, null=True)),
                ('ACH-000430', models.FloatField(blank=True, null=True)),
                ('ACH-001418', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
