# Generated by Django 5.1.2 on 2025-04-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_drug_gdsc1_auc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug_GDSC1_AUC',
            new_name='DrugScreen',
        ),
        migrations.RenameModel(
            old_name='Mole_GlobalChromatin',
            new_name='Molecular',
        ),
    ]
