# Generated by Django 5.1.2 on 2025-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_clinical_tcga_tcga_23_1021_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1021',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1022',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1023',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1024',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1026',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1027',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1028',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1029',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1030',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1031',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1032',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1107',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1109',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1110',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1111',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1113',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1114',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1116',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1117',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1118',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1119',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1120',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1121',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1122',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1123',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-1809',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2072',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2077',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2078',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2079',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2081',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2084',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2641',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2643',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2645',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2647',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-23-2649',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1312',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1313',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1314',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1315',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1316',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1317',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1318',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1319',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1320',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1321',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1322',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1323',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1324',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1325',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1326',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1328',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1329',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1623',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1625',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1626',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1627',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1630',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1631',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1632',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1634',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1635',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1870',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1871',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1877',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-1878',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2042',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2390',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2391',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2392',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2393',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2396',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2397',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2399',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2400',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2401',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2404',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2408',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-25-2409',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-3P-A9WA',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2582',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2587',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2588',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2589',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2590',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2591',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-42-2593',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1582',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1583',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1585',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1586',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1992',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1993',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-57-1994',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-59-A5PD',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-5X-AA5U',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-OY-A56P',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-OY-A56Q',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_tcga',
            name='TCGA-WR-A838',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
